---
abstract: 'Collection of useful Utils'
author:
  - 'Sergey Pankov <vacuum@ivacuum.ru>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ivacuum-Utils
provides:
  Ivacuum::Utils:
    file: lib/Ivacuum/Utils.pm
    version: v1.0.3
  Ivacuum::Utils::BitTorrent:
    file: lib/Ivacuum/Utils/BitTorrent.pm
    version: v1.0.3
  Ivacuum::Utils::DB:
    file: lib/Ivacuum/Utils/DB.pm
    version: v1.0.3
  Ivacuum::Utils::HTTP:
    file: lib/Ivacuum/Utils/HTTP.pm
    version: v1.0.3
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: v1.0.3
